### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by FedeG** [lelylan/types#36]
Error:
```bash
Step 13/15 : RUN bundle install
...
Downloading activerecord-3.2.14 revealed dependencies not in the API
(activesupport (= 3.2.14), activemodel (= 3.2.14), arel (~> 3.0.2), tzinfo (~>
0.3.29)).
Installing with `--full-index` should fix the problem.
The command '/bin/sh -c bundle install' returned a non-zero code: 34
```

Solution: "Installing with `--full-index` should fix the problem."

**Comment by murugespandian** [comment]
while executing, bundle install --full-index got the below print..

Fetching source index from http://rubygems.org/
Killed

????

**Comment by andreareginato** [comment]
@murugespandian Can't see the print. Am I missing something?

**Comment by murugespandian** [comment]
@andreareginato .I got the above print only. That is due to some old gems problem. Now its working. One more doubt..?,Lelylan works on Vagrant  right..?For testing.. If yes,do we need to configure anything special on vagrant..?. Following manual installation.
